### ISSUE TITLE
Class 'ipinfo\ipinfo\Exception' not found

### ISSUE THREAD

**Issue by dmitriy2018** [ipinfo/php#1]
Executing getDetails with fake IP produces fatal error.

`$ip = '34535';
$IPInfoClient->getDetails($ip);`

Add `use \Exception;` into IPInfo.php

**Comment by rvalitov** [comment]
Add in PHPDoc that the function may rise an Exception

**Comment by scofield-ua** [comment]
@coderholic

**Comment by coderholic** [comment]
@jhtimmins

**Comment by jhtimmins** [comment]
@coderholic @scofield-ua I'll take a look later today and will fix/close this issue.

**Comment by jhtimmins** [comment]
@scofield-ua my apologies, I ran into some issues with my computer so I'm having trouble testing this, which may delay me a bit. 

In the meantime, could you clarify why it's necessary to import Exceptions from multiple locations?

**Comment by rvalitov** [comment]
@jhtimmins, the comment of @scofield-ua is absolutely correct. That's what have been done in my PR #5 
Additionally I added the correct information about the exceptions in PHPDoc.

**Comment by jhtimmins** [comment]
@scofield-ua Ah of course, yes that makes sense. I actually thought you submitted the PR with multiple exception types, which should have been directed at the PR author. Thanks for the info.

@rvalitov Could you explain this docblock, and why it includes two exception types?
```
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @throws \Exception
```

It doesn't look like `\GuzzleHttp\Exception\GuzzleException` will ever get thrown directly. Or am I missing something?

**Comment by rvalitov** [comment]
@jhtimmins 
A function definition must include all uncatched exceptions. The exceptions may rise inside the function code or inside other functions that your original function calls. The functions that you call use Guzzle, and Guzzle functions throw `\GuzzleHttp\Exception\GuzzleException`. You don't catch exceptions from Guzzle therefore you pass them to the user. As a result you have to specify the `\GuzzleHttp\Exception\GuzzleException` in the PHPDoc.

**Comment by jhtimmins** [comment]
This was fixed in commit https://github.com/ipinfo/php/commit/6068f655b5601142035b901331d9c1752d95c1c2.

I've added an `IPinfoException` class which will get returned instead of the base `Exception` class or the `GuzzleException` class.

**Comment by Acrash79** [comment]
😊

**Comment by UmanShahzad** [comment]
If https://github.com/ipinfo/php/commit/6068f655b5601142035b901331d9c1752d95c1c2 does not resolve this issue, please let me know and we can reopen.
